name: WarpMagic
version: ${project.version}
main: com.eclipsekingdom.warpmagic.WarpMagic
api-version: 1.13
authors: [sword]
description: A teleportation management plugin
website: eclipsekingdom.com

commands:
  home:
  fhome:
  warp:
  warpstone:
  vortex:
  vortexstone: