name: WarpMagic
version: ${project.version}
main: com.eclipsekingdom.warpmagic.WarpMagic
api-version: 1.13
authors: [sword]
description: A teleportation management plugin
website: eclipsekingdom.com

load: POSTWORLD

commands:
  warpmagic:
  we:
  effectstone:
  home:
  fhome:
  warp:
  warpstone:
  vortex:
  vortexstone:
  spawn:
  setspawn:
  hub:
  sethub:
  tpa:
  tpdeny:
  tpaccept:
  tpahere:
  jump:
  top:
  bottom: